version: 2

workflows:
  version: 2
  all_tests:
    - linters
    - tests


jobs:
  linters:
    docker:
    # Image to run the tests in
      - image: circleci/python:3.6.5-stretch-browsers
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test

    steps:
      - checkout

      - run: # run linters
          name: run linting and metrics
          command: |
            . venv/bin/activate
            flake8 metaswitch_tinder --output-file flake8-report
            mypy metaswitch_tinder --ignore-missing-imports

      - store_artifacts:
          path: flake8-report
          destination: flake8-report

  tests:
    docker:
    # Image to run the tests in
      - image: circleci/python:3.6.5-stretch-browsers
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test

    # Postgres database container image
      - image: circleci/postgres:9.6.5-alpine-ram
        environment: # environment variables for database
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - restore_cache: # restores saved dependency cache if the Branch key template or setup.py files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run: # install and activate virtual environment with pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r test_requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"

      - run: # initialise database
          command: |
            . venv/bin/activate
            python tests/init_database.py

      - run: # run tests
          command: |
            . venv/bin/activate
            python setup.py test
